= MySkills Deployment
Georg Wittberger <georg.wittberger@gmail.com>
v0.0.1, 2018-10-03

This repository provides templates for different kinds of deployments of the MySkills application.

== Using Docker Compose

The subdirectory `docker-compose` contains a template to deploy MySkills using Docker Compose. This is an ideal solution for local development and testing environments. *It is NOT recommended for production!*

=== Prerequisites

* Docker 17.06.0 (or higher)
* Docker Compose 1.17.0 (or higher)
* Git Client

=== Deployment with pre-built images

IMPORTANT: We do not publish Docker images so far. This deployment approach assumes that you have pre-built the images `myskills/webapp:latest` and `myskills/server:latest` on the Docker daemon which will run the containers!

. Clone this Git repository.
. Open a terminal in the subdirectory `docker-compose`.
. Export the environment variable `SERVER_DOMAIN` to define the web domain where the MySkills WebApp will be hosted. For example: `SERVER_DOMAIN=myskills.your-domain.com`. Default is `localhost`.
. Export the environment variable `SERVER_ADMIN` to define the admin's e-mail address (just for internal configuration). For example: `SERVER_ADMIN=admin@your-domain.com`. Default is `anonymous@nothing.com`.
. Start the deployment: `docker-compose -p myskills up -d`
. Verify the container state: `docker-compose -p myskills ps`
. Configure the KeyCloak realm after the first deployment. Go to http://myskills.your-domain.com:9000/auth and follow the instructions in the section <<Configuring authentication using KeyCloak>>.
. Visit http://myskills.your-domain.com/ to view the MySkills WebApp.

=== Deployment from sources

The MySkills Server and WebApp can be deployed directly from sources using the bash script `deploy-from-sources.sh`. The script fetches the sources from GitHub, compiles the applications and builds their Docker images. Then it starts the Docker Compose deployment as described above.

. Clone this Git repository.
. Open a terminal in the subdirectory `docker-compose`.
. Export the environment variable `SERVER_DOMAIN` to define the web domain where the MySkills WebApp will be hosted. For example: `SERVER_DOMAIN=myskills.your-domain.com`. Default is `localhost`.
. Export the environment variable `SERVER_ADMIN` to define the admin's e-mail address (just for internal configuration). For example: `SERVER_ADMIN=admin@your-domain.com`. Default is `anonymous@nothing.com`.
. Optionally export the environment variable `BUILD_CONTEXT_DIR` to define the directory where the sources and build caches should be stored. Default is `$HOME/myskills`.
. Optionally export the environment variables `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` if HTTP connections to the internet must be established via a proxy server. For example: `HTTP_PROXY=http://proxy.company.com:8080 ; NO_PROXY=localhost,127.0.0.1`
. Start the deployment: `./deploy-from-sources.sh`
. Verify the container state: `docker-compose -p myskills ps`
. Configure the KeyCloak realm after the first deployment. Go to http://myskills.your-domain.com:9000/auth and follow the instructions in the section <<Configuring authentication using KeyCloak>>.
. Visit http://myskills.your-domain.com/ to view the MySkills WebApp.

== Configuring authentication using KeyCloak

. Install the KeyCloak server.
. Log in to the KeyCloak administration console.
. Create a new realm named `MySkills`.
. Create a new client within the `MySkills` realm:
  * Client ID: `myskills`
  * Client Protocol: `openid-connect`
  * Root URL: (Base URL where the MySkills WebApp is hosted), e.g. `http://myskills.your-domain.com`
. Configure the client settings:
  * Access Type: `public`
  * Standard Flow Enabled: `off`
  * Implicit Flow Enabled: `on`
  * Valid Redirect URIs:
  ** `/`
  ** `/index.html`
  ** `/silent-refresh.html`
  * Web Origins: (Base URL where the MySkills WebApp is hosted), e.g. `http://myskills.your-domain.com`
. Configure the mappers of the client scope `profile`:
  * For the mapper `username` set the Token Claim Name to `user_name`
. Configure users and groups as needed.

== License

https://opensource.org/licenses/MIT[MIT]
